environment:
  matrix:
    - PY_MAJOR_VER: 3
      MINICONDA_SUFFIX: 36

install:
  - set CONDA_ROOT="C:\Miniconda%MINICONDA_SUFFIX%-x64"
  - set PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%
  #- set PATH=%PATH%;C:\msys64\usr\bin
  #- conda update -y --all
  - conda install -y cmake swig
  - swig -swiglib

build_script:
  - mkdir build && cd build
  - cmake -LAH -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%CD:\=/%/install -DSWIG_DIR="C:/Miniconda36-x64/Library/bin/Lib" -DPYTHON_EXECUTABLE=C:/Miniconda%MINICONDA_SUFFIX%-x64/python.exe -DPYTHON_LIBRARY=C:/Miniconda%MINICONDA_SUFFIX%-x64/libs/python36.lib ..
  - cmake --build . --config RelWithDebInfo --target install
  - set PYTHONPATH=%cd%\install\Lib\site-packages
  - ctest --output-on-failure -C RelWithDebInfo
